### ISSUE TITLE
[Medium] 8. String to Integer (atoi)

### ISSUE THREAD

**Issue by dglalperen** [dglalperen/Leetcode#1]
#### Problem Statement

Implement the `myAtoi(string s)` function, which converts a string to a 32-bit signed integer (similar to C/C++'s `atoi` function).

The algorithm for `myAtoi(string s)` is as follows:

1. **Read in and ignore any leading whitespace.**
2. **Check if the next character (if not already at the end of the string) is '-' or '+'.** 
    - Read this character in if it is either. This determines if the final result is negative or positive respectively. Assume the result is positive if neither is present.
3. **Read in the next characters until the next non-digit character or the end of the input is reached.**
    - The rest of the string is ignored.
4. **Convert these digits into an integer** 
    - (i.e., "123" -> 123, "0032" -> 32). 
    - If no digits were read, then the integer is 0. 
    - Change the sign as necessary (from step 2).
5. **Clamping**: 
    - If the integer is out of the 32-bit signed integer range \[-2^31, 2^31 - 1\], then clamp the integer so that it remains in the range.

**Note:**
- Only the space character ' ' is considered a whitespace character.
- Do not ignore any characters other than the leading whitespace or the rest of the string after the digits.

#### Constraints:
- 0 <= s.length <= 200
- s consists of English letters (lower-case and upper-case), digits (0-9), ' ', '+', '-', and '.'.

#### Example Test Cases:

1. **Input**: `s = "42"`  
   **Output**: `42`

2. **Input**: `s = "   -42"`  
   **Output**: `-42`

3. **Input**: `s = "4193 with words"`  
   **Output**: `4193`

#### Tasks:
- [ ] Implement the solution in Python
- [ ] Implement the solution in Java
- [ ] Write unit tests for the implementations
- [ ] Update README with the problem and solutions
