### ISSUE TITLE
**[Easy] 1. Two Sum**

### ISSUE THREAD

**Issue by dglalperen** [dglalperen/Leetcode#2]
#### Problem Statement

Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

You can return the answer in any order.

#### Example:

**Input**: `nums = [2, 7, 11, 15], target = 9`  
**Output**: `[0, 1]`  
**Explanation**: `nums[0] + nums[1] == 9`

#### Constraints:

- `2 <= nums.length <= 10^4`
- `-10^9 <= nums[i] <= 10^9`
- `-10^9 <= target <= 10^9`
- Only one valid answer exists.

#### Tasks:

- [ ] Implement the solution in Python
- [ ] Write unit tests for the implementation
- [ ] Update README with the problem and solutions
